### dev ###

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.8:15432/postgres
    username: postgres
    password: postgres1234!@#$
    hikari:      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:    database: postgresql

security:
  login:
    url: /login.do
  loginProc:
    url: /loginProc.do
  logout:
    url: /logout.do
    
page:
  root:
    url: /
  main:
    url: /main.do

api:
  get:
    url: https://httpbin.org/get
  post:
    url: https://httpbin.org/post