### release ###

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.16:25432/postgres
    username: postgres
    password: postgres!@#$%12345
    hikari:      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:    database: postgresql
  thymeleaf:
    cache: true

security:
  login:
    url: /login.do
  loginProc:
    url: /loginProc.do
  logout:
    url: /logout.do

logging:
  file:
    path: /home/user/tomcat/logs
    name: demo
server:
  port: 8080
  error:
    path: /error

page:
  root:
    url: /
  main:
    url: /main.do

api:
  get:
    url: https://httpbin.org/get
  post:
    url: https://httpbin.org/post
    
mail:
  sender:
    id: test@mail.com
    pwd: qwe123!@#
    host: smtp.naver.com
    port: 465
    auth: true
    ssl:
      enable: true
      host: smtp.naver.com