### release ###

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.16:25432/postgres
    username: postgres
    password: postgres!@#$%12345
    hikari:      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:    database: postgresql
  thymeleaf:
    cache: true

security:
  login:
    url: /login.do
  loginProc:
    url: /loginProc.do
  logout:
    url: /logout.do

server:
  error:
    path: /error

page:
  root:
    url: /
  main:
    url: /main.do

api:
  get:
    url: https://httpbin.org/get
  post:
    url: https://httpbin.org/post